voyage_users_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: voyageUsersBundle:Default:index }
login:
    pattern:  /login
    defaults: { _controller: voyageUsersBundle:Default:login }
register:
    pattern:  /register
    defaults: { _controller: voyageUsersBundle:Default:register }
login_check:
    pattern: /login_check

logout:
    pattern: /logout
