parameters:
#    voyage_users.example.class: voyage\UsersBundle\Example

services:
#    voyage_users.example:
#        class: %voyage_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
