voyage_homepage:
    pattern:  /
    defaults: { _controller: VoyageBundle:Default:index }

voyage_contact:
    pattern:  /contact
    defaults: { _controller: VoyageBundle:Default:contact }
    

recherche:
    pattern:  /recherche
    defaults: { _controller: VoyageBundle:Recherche:recherche }
recherche2:
    pattern:  /recherche2
    defaults: { _controller: VoyageBundle:Recherche:recherche2 }
       
stat:
    pattern:  /inscription
    defaults: { _controller: VoyageBundle:Default:stat }    

    
inscription:
    pattern:  /inscription
    defaults: { _controller: VoyageBundle:Users:inscription }
profil:
    pattern:  /profil
    defaults: { _controller: VoyageBundle:Users:profil }







annonce:
    pattern:  /annonce
    defaults: { _controller: VoyageBundle:Annonce:index }
annonce2:
    pattern:  /annonce/index2
    defaults: { _controller: VoyageBundle:Annonce:index2 }
annonce_show:
    pattern:  /annonce/show/{id}
    defaults: { _controller: VoyageBundle:Annonce:show }
annonce_edit:
    pattern:  /annonce/edit/{id}
    defaults: { _controller: VoyageBundle:Annonce:edit }
annonce_new:
    pattern:  /annonce/new
    defaults: { _controller: VoyageBundle:Annonce:new }
annonce_create:
    pattern:  /annonce/create
    defaults: { _controller: VoyageBundle:Annonce:create }
annonce_delete:
    pattern:  /annonce/delete/{id}
    defaults: { _controller: VoyageBundle:Annonce:delete }
annonce_update:
    pattern:  /annonce/update/{id}
    defaults: { _controller: VoyageBundle:Annonce:update }
    
    
add_comment:
    pattern:  /annonce/add/{id}
    defaults: { _controller: VoyageBundle:Eval:add }

proposition:
    pattern:  /Proposition
    defaults: { _controller: VoyageBundle:Proposition:index }
proposition_show:
    pattern:  /Proposition/show/{id}
    defaults: { _controller: VoyageBundle:Proposition:show }
proposition_edit:
    pattern:  /Proposition/edit/{id}
    defaults: { _controller: VoyageBundle:Proposition:edit }
proposition_new:
    pattern:  /Proposition/new
    defaults: { _controller: VoyageBundle:Proposition:new }
proposition_create:
    pattern:  /Proposition/create
    defaults: { _controller: VoyageBundle:Proposition:create }
proposition_delete:
    pattern:  /Proposition/delete/{id}
    defaults: { _controller: VoyageBundle:Proposition:delete }
proposition_update:
    pattern:  /Proposition/update/{id}
    defaults: { _controller: VoyageBundle:Proposition:update }
       
   
   
 
   
confirmer_reservation: 
    pattern: /reservationsC 
    defaults: { _controller: VoyageBundle:Reservation:email }
reservationsShow: 
    pattern: /reservations/all 
    defaults: { _controller: VoyageBundle:Reservation:ShowReservations }
annuler_reservation: 
    pattern: /reservationsA 
    defaults: { _controller: VoyageBundle:Reservation:emaila }   