user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UserBundle:Default:index }
_security_check_facebook:
    pattern:   /facebook/login_check
    defaults:  { _controller: UserBundle:User:loginFb }

_security_facebook_logout:
  pattern:  /facebook/logout

user_couple_fb_with_account:
    pattern: /user/couple/facebook
    defaults: { _controller: UserBundle:User:connectFacebookWithAccount }